version: '3.8'

services:
  domain-controller:
    build: .
    container_name: quantummint-domain-controller
    ports:
      - "389:389"   # LDAP
      - "636:636"   # LDAPS
      - "88:88"     # Kerberos
      - "53:53/udp" # DNS
      - "8080:8080" # Web API
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/quantummint-domain
      - REDIS_URI=redis://redis:6379
      - DOMAIN_NAME=quantummint.local
      - LDAP_BASE_DN=dc=quantummint,dc=local
      - JWT_SECRET=your-production-jwt-secret-change-this
      - ENCRYPTION_KEY=your-32-char-encryption-key-here
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
    networks:
      - quantummint-network
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: quantummint-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=quantummint-domain
    volumes:
      - mongo-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - quantummint-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: quantummint-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - quantummint-network
    restart: unless-stopped

  # Optional: MongoDB Express for database management
  mongo-express:
    image: mongo-express:latest
    container_name: quantummint-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    networks:
      - quantummint-network
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data:

networks:
  quantummint-network:
    driver: bridge
