version: '3.8'

services:
  # Database
  mongodb:
    image: mongo:5.0
    container_name: quantummint-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=quantummint
    networks:
      - quantummint-network

  # Redis for caching and session management
  redis:
    image: redis:6.2-alpine
    container_name: quantummint-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quantummint-network

  # RabbitMQ for messaging
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: quantummint-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=quantummint
      - RABBITMQ_DEFAULT_PASS=quantummint
    networks:
      - quantummint-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: quantummint-api-gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/quantummint
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URI=amqp://quantummint:quantummint@rabbitmq:5672
      - AUTH_SERVICE_URL=http://auth-service:3001
      - MONEY_GENERATION_SERVICE_URL=http://money-generation:3002
      - TRANSACTION_SERVICE_URL=http://transaction-service:3003
      - PAYMENT_INTEGRATION_SERVICE_URL=http://payment-integration:3004
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - quantummint-network

  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: quantummint-auth-service
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/quantummint
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URI=amqp://quantummint:quantummint@rabbitmq:5672
      - JWT_SECRET=your_jwt_secret_key
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key
      - JWT_EXPIRATION=1h
      - JWT_REFRESH_EXPIRATION=7d
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - quantummint-network

  # Money Generation Service
  money-generation:
    build:
      context: ./money-generation
      dockerfile: Dockerfile
    container_name: quantummint-money-generation
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/quantummint
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URI=amqp://quantummint:quantummint@rabbitmq:5672
    volumes:
      - ./money-generation:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - quantummint-network

  # Transaction Service
  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    container_name: quantummint-transaction-service
    restart: always
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/quantummint
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URI=amqp://quantummint:quantummint@rabbitmq:5672
    volumes:
      - ./transaction-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - quantummint-network

  # Payment Integration Service
  payment-integration:
    build:
      context: ./payment-integration
      dockerfile: Dockerfile
    container_name: quantummint-payment-integration
    restart: always
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGODB_URI=mongodb://mongodb:27017/quantummint
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_URI=amqp://quantummint:quantummint@rabbitmq:5672
      - ORANGE_MONEY_API_URL=https://api.orange-money.com
      - ORANGE_MONEY_TOKEN_URL=https://oauth.orange-money.com/token
      - ORANGE_MONEY_CLIENT_ID=your_orange_money_client_id
      - ORANGE_MONEY_CLIENT_SECRET=your_orange_money_client_secret
      - ORANGE_MONEY_WEBHOOK_SECRET=your_orange_money_webhook_secret
      - AFRIMONEY_API_URL=https://api.afrimoney.com
      - AFRIMONEY_API_KEY=your_afrimoney_api_key
      - AFRIMONEY_API_SECRET=your_afrimoney_api_secret
      - AFRIMONEY_WEBHOOK_SECRET=your_afrimoney_webhook_secret
      - STRIPE_API_KEY=your_stripe_api_key
      - STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret
    volumes:
      - ./payment-integration:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - quantummint-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quantummint-frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api-gateway
    networks:
      - quantummint-network

networks:
  quantummint-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  rabbitmq_data: